name: flutter_application_9
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-200.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter: 
uses-material-deisgn: true
assets: 
   - assets/img/perfil.jpg
   - assets/img/perfil2.jpg
   - assets/img/perfil3.jpg
   - assets/img/perfil4.jpg
   - assets/img/lugar1.jpg
   - assets/img/lugar2.jpg
   - assets/img/lugar3.jpg
   - assets/img/lugar4.jpg
   - assets/img/lugar5.jpg
   - assets/img/lugar6.jpg
   - assets/img/lugar7.jpg
